### ISSUE TITLE
How to specify the time zone configuration when creating a cluster?

### ISSUE THREAD

**Issue by zhangao4833** [radondb/radondb-postgresql-operator#21]
How to specify the time zone configuration when creating a cluster？Generally, the container can be specified with PGTZ environment variable, but I can't find the corresponding parameter configuration in the help document.

**Comment by zhl003** [comment]
Default time zone base on your local machine, our container hasn't a parameter  to specify timezone ,but  this not a problem ,PG has very convenient way to set timezone for client or server side , example :
session level / user level /db level just run SQL `set timezone xxx` or `alter database xx set timezone =xxx` 
if you want  take effect after restart, you can edit the global config configmap like this :
```shell
kubectl edit cm -n pgo  demo-pgha-config
# Add below to data/demo-dcs-config/postgresql/parameters
        log_timezone : 'US/Pacific'
        timezone :q 'US/Pacific'
then reload/restart postgresql cluster :
pgo reload demo -n pgo/pgo restart demo -n pgo
```
