### ISSUE TITLE
 编译问题

### ISSUE THREAD

**Issue by killerwzb** [radondb/radondb-postgresql-operator#22]
您好：
    我在尝试使用make构建程序和镜像，好像目前centos8的仓库已经失效了，我在centos-8.repo文件里进行了相应的替换，另外当构建pgo-base镜像时，提示有问题：

Unable to resolve argument postgresql
Error: Problems in request:
missing groups or modules: postgresql
error building at STEP "RUN if [ "$BASEOS" = "centos8" ]; then     ${PACKAGER} -y update     && ${PACKAGER} -y install         --setopt=skip_missing_names_on_install=False         glibc-langpack-en     && ${PACKAGER} -y clean all     && ${PACKAGER} -qy module disable postgresql ; fi": error while running runtime: exit status 1
make: *** [pgo-base-build] Error 1

不知道您这边之前是如何编译成功的。

**Comment by zhl003** [comment]
It seems something wrong with Ali mirror repo. Am testing with it ,If any progress I will get back to you here 
by the way ,you can try any other repo that available ,just replace  URL in Centos8.repo

**Comment by killerwzb** [comment]
OK.
