### ISSUE TITLE
如何设置pvc的大小

### ISSUE THREAD

**Issue by bocblca** [radondb/radondb-postgresql-operator#38]
我按照指引安装了radondb postgresql pgo,但是自动生成的的PVC都是1G的：
[rcbpsql-pgbr-repo](https://192.168.100.208:30012/#/persistentvolumeclaim/net6/rcbpsql-pgbr-repo?namespace=_all)
net6
pg-cluster: rcbpsql
vendor: radondb
Bound
[pvc-e9a87c01-8bee-4c29-b0ce-de64f1cb1093](https://192.168.100.208:30012/#/persistentvolume/pvc-e9a87c01-8bee-4c29-b0ce-de64f1cb1093?namespace=_all)
1G
ReadWriteOnce
managed-nfs-storage
9 minutes ago
[rcbpsql](https://192.168.100.208:30012/#/persistentvolumeclaim/net6/rcbpsql?namespace=_all)
net6
pg-cluster: rcbpsql
vendor: radondb
Bound
[pvc-70fc59f1-b8b8-462a-a7da-d8e1c07128ed](https://192.168.100.208:30012/#/persistentvolume/pvc-70fc59f1-b8b8-462a-a7da-d8e1c07128ed?namespace=_all)
1G
ReadWriteOnce
managed-nfs-storage
9 minutes ago

我的storageclass 是动态默认的，也可以自动扩容，有什么办法控制PVC的大小吗？还是说如果使用超过1g,程序会自动扩容？
感谢支持！
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhl003** [comment]
你可以看下pgo的命令行帮助，在创建集群的时候可以设置pvc的大小，此外安装完集群也可以调整磁盘的大小，初始化安装只有1G

**Comment by bocblca** [comment]
> 你可以看下pgo的命令行帮助，在创建集群的时候可以设置pvc的大小，此外安装完集群也可以调整磁盘的大小，初始化安装只有1G

我用pgo help 查了一下没看到指定pvc大小的命令啊？请指教，谢谢。安装完是能调节，我试过了。命令行怎么用，麻烦说一下，谢了！

**Comment by bocblca** [comment]
> 你可以看下pgo的命令行帮助，在创建集群的时候可以设置pvc的大小，此外安装完集群也可以调整磁盘的大小，初始化安装只有1G

我在网上查了一下pgo，在github上有这么写的，不知是否适用？
pgo create cluster --pvc-size 100Gi --pgbackrest-pvc-size 100Gi --storage-config=nfsstorage --pgbouncer \
  --pgbouncer-service-type=NodePort --service-type=NodePort --pgbadger --metrics \
  --restore-from pg0 --restore-opts "--

**Comment by zhl003** [comment]
> 

是的 ，就是这样的

**Comment by zhl003** [comment]
> > 你可以看下pgo的命令行帮助，在创建集群的时候可以设置pvc的大小，此外安装完集群也可以调整磁盘的大小，初始化安装只有1G
> 
> 我在网上查了一下pgo，在github上有这么写的，不知是否适用？ pgo create cluster --pvc-size 100Gi --pgbackrest-pvc-size 100Gi --storage-config=nfsstorage --pgbouncer --pgbouncer-service-type=NodePort --service-type=NodePort --pgbadger --metrics --restore-from pg0 --restore-opts "--

```pgo create cluster --help```

**Comment by bocblca** [comment]
已确认可以pgo设置pvc大小

**Comment by KID-G** [comment]
> 已确认可以pgo设置pvc大小

Hi，可以添加社区管理员微信号：radondb，加入 RadonDB 开源社区社群，进行问题讨论。
